# Generated by Django 4.2.1 on 2023-06-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('nomEntreprise', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('adresse', models.CharField(default='', max_length=255, null=True)),
                ('telephone', models.CharField(default='', max_length=25, null=True)),
                ('siteWeb', models.CharField(default='', max_length=255, null=True)),
                ('codeEntreprise', models.CharField(default='', max_length=255, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='images/company/')),
            ],
            options={
                'db_table': 'companyAdmins',
                'ordering': ['nomEntreprise'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('typee', models.CharField(default='', max_length=255, null=True)),
                ('experience', models.IntegerField(default=0, null=True)),
                ('adresse', models.CharField(default='', max_length=255, null=True)),
                ('deadLine', models.DateField(default='2023-06-15', null=True)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.companyadmin')),
            ],
            options={
                'db_table': 'offres',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('userName', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'superAdmins',
                'ordering': ['userName'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('nom', models.CharField(default='', max_length=255, null=True)),
                ('prenom', models.CharField(default='', max_length=255, null=True)),
                ('userName', models.CharField(default='', max_length=255, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='images/users/')),
                ('adresse', models.CharField(default='', max_length=400, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('telephone', models.CharField(default='', max_length=25, null=True)),
                ('lettreMotivation', models.FileField(default='', null=True, upload_to='userLettresMotivation/')),
                ('cv', models.FileField(default='', null=True, upload_to='userCv/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.superadmin')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['userName'],
            },
        ),
        migrations.CreateModel(
            name='PostuleOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePostuler', models.DateField(default='2023-06-15', null=True)),
                ('etat', models.BooleanField(default=False)),
                ('offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offre')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'postuleOffres',
                'ordering': ['datePostuler'],
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='postules',
            field=models.ManyToManyField(through='api.PostuleOffre', to='api.user'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.superadmin'),
        ),
    ]
