# Generated by Django 4.1.7 on 2023-04-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='23-04-25 16:58:05'),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='25/04/23 16:58:05'),
        ),
    ]
