# Generated by Django 4.2.1 on 2023-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_offre_deadline_alter_postuleoffre_datepostuler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='2023-06-17', null=True),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='2023-06-17', null=True),
        ),
    ]
