# Generated by Django 4.1.7 on 2023-04-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_offre_deadline_alter_postuleoffre_datepostuler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='23-04-25 17:03:32'),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='25/04/23 17:03:32'),
        ),
    ]
