# Generated by Django 4.1.7 on 2023-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_offre_deadline_alter_postuleoffre_datepostuler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Expérience',
            new_name='Experience',
        ),
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='23-04-25'),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='25/04/23 17:04:00'),
        ),
    ]
