# Generated by Django 4.1.7 on 2023-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_expérience_offre_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='25/04/23 17:05:37'),
        ),
    ]
