# Generated by Django 4.1.7 on 2023-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_postuleoffre_datepostuler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='2023-04-25'),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='2023-04-25'),
        ),
    ]
