# Generated by Django 4.1.7 on 2023-04-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_offre_deadline_alter_postuleoffre_datepostuler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Postules',
            new_name='postules',
        ),
    ]
