# Generated by Django 4.1.7 on 2023-05-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_companyadmin_last_login_superadmin_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
