# Generated by Django 4.1.7 on 2023-05-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_companyadmin_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='image',
            field=models.ImageField(default='', upload_to='images/jobs/'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='2023-05-23'),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='2023-05-23'),
        ),
    ]
