# Generated by Django 4.1.7 on 2023-05-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_offre_image_alter_offre_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Experience',
            new_name='experience',
        ),
    ]
