# Generated by Django 4.1.7 on 2023-05-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_experience_offre_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='adresse',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='codeEntreprise',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='nomEntreprise',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='siteWeb',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='telephone',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='adresse',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='deadLine',
            field=models.DateField(default='2023-05-24', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/jobs/'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='postules',
            field=models.ManyToManyField(null=True, through='api.PostuleOffre', to='api.user'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='titre',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='typee',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postuleoffre',
            name='datePostuler',
            field=models.DateField(default='2023-05-24', null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='userName',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(default='', null=True, upload_to='userCv/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lettreMotivation',
            field=models.FileField(default='', null=True, upload_to='userLettresMotivation/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
